### ISSUE TITLE
Den 28

### ISSUE THREAD

**Issue by okst** [jankonzal/Exodus90#3]
Překlad citace sv. Jana Zlatoústého z webu jesuit.cz:

_Chceš po znat moc Kristovy krve? Pak se vraťme k jejímu předobrazu, k dávným příběhům, jak se odehrály v Egyptě.
Zabijte, říká Mojžíš, beránka, na němž není vady, a jeho krví pomažte dveře. Co to znamená? Že krev zvířete je schopna spasit rozumného člověka? Zajisté, říká, ale nikoli proto, že je to krev, nýbrž proto, že je předobrazem krve Páně. Jestliže Ďábel nyní uvidí nikoli krev předobrazu rozetřenou po dveřích, nýbrž krev pravdy nanesenou ústy věrných na dveře Chrámu, v němž spočívá Kristus, což se tím spíše nestáhne zpět?_

(Z katechezí svatého Jana Zlatoústého, biskupa, in SCh 50, s. 158–162; lat. s. 174–177)

**Comment by okst** [comment]
Už jsem to vložil přímo do textu jako návrh změny.

**Comment by jankonzal** [comment]
Supr vůbec mě nenapadlo, že by tohle šlo dohledat. Díky!

**Comment by jankonzal** [comment]
Tvůj návrh změny se mi zu nezobrazuje. Musíš okomentovat commit i pull request. Už jsem to commitnul sám. Díky

**Comment by jankonzal** [comment]
Tvůj návrh změny se mi zu nezobrazuje. Musíš okomentovat commit i pull request. Už jsem to commitnul sám. Díky
